config/routes.rb
Rails.application.routes.draw do
  resources :leads

  root 'leads#new'

end

app/models/lead.rb
class Lead < ActiveRecord::Base

	validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.js { render status: 200 }
        format.json { render :show, status: :created, location: @lead }
        LeadMailer.early_access(@lead).deliver_now
        LeadMailer.internal_notification(@lead).deliver_now
      else
        format.html { render :new }
        format.js { render status: 500 }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:email, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/old.html.erb
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <!-- TITLE OF SITE -->
    <title>ServiceLink | Mobile Forms for HVAC</title>

    <meta name="description" content="Responsive Landing Page for Presenting Your Startup: Saas, Mobile or Web Application" />
    <meta name="keywords" content="smartmvp, startup theme, startup template, startup example, startup landing page, one page, responsive, app landing, html template, mobile application, responsive landing page" />
    <meta name="author" content="ThemeDept">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- FAVICON  -->
    <link rel="icon" href="/smartmvp/images/favicon/favicon.ico">
    
    <!-- =========================
       STYLESHEETS 
    ============================== -->
    
    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="/smartmvp/css/plugins/bootstrap.min.css">

    <!-- FONT ICONS -->
    <link rel="stylesheet" href="/smartmvp/css/icons/icons.min.css">
     
    <!-- GOOGLE FONTS -->
    <link href="http://fonts.googleapis.com/css?family=Raleway:300,400,600,700%7COpen+Sans:300,400,600,700%7CHandlee" rel="stylesheet">
    
    <!-- PLUGINS STYLESHEET -->
    <link rel="stylesheet" href="/smartmvp/css/plugins/plugins.min.css">
    
    <!-- CUSTOM STYLESHEET -->
    <link rel="stylesheet" href="/smartmvp/css/style.css">

    <!-- RESPONSIVE FIXES -->
    <link rel="stylesheet" href="/smartmvp/css/responsive.css">

    <!-- COLORE STYLESHEET -->
    <!-- Change here the Main Color of the Site: Choose your favorite predefined color from assets/css/colors.css -->
    <link rel="stylesheet" href="/smartmvp/css/colors/blue.css" title="red">

    <link rel="stylesheet" href="/smartmvp/css/custom.css">
    
    
    <!--[if lt IE 9]>
            <script src="assets/js/plugins/html5shiv.min.js"></script>
            <script src="assets/js/plugins/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
</head>

<body>
    <!-- =========================
         PRELOADER
    ============================== -->
    <div class="preloader">
        <div class="loader-container">
            <div class="text-logo">ServiceLink</div>
            <div class="signal"></div>
        </div>
    </div> 
    

    <!-- =========================
         HEADER
    ============================== -->
    <header class="header" id="top" data-stellar-background-ratio="0.5">
        <!-- Background Overlay -->
        <div class="overlay">

            <!-- =========================================
                 Navigation
            ========================================== -->
            <nav class="navbar navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- Navbar-Header -->
                            <div class="navbar-header">

                                <!-- Text-Logo -->
                                <a href="#top" class="navbar-brand scrollto" title="SmartMvp">
                                    <span class="text-logo">ServiceLink</span>
                                </a> 

                                <!-- Image-Logo: Remove this comments and the section above Text-Logo if you want to add an Image-Logo (recommended sizes -> max-height:50, max-width:200) 

                                <a href="#top" class="navbar-brand img-logo scrollto" title="SmartMvp">
                                    <img src="assets/images/logo.png" alt="Logo">
                                </a> 
                                -->

                            </div><!-- /End Navbar-Header -->


                        </div><!-- /End Col -->
                    </div><!-- /End Row -->
                </div><!-- /End Container -->
            </nav><!-- /End Sticky Navigation -->


            <!-- =========================================
                 Hero-Section
            ========================================== -->
            <div class="container vmiddle earlyaccess">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="hero-section">
                            
                            <!-- Welcome - Hero Message -->
                            <h1 class="text-white">Mobile Forms Your Technicians Will Love</h1>
                            <p class="text-white">Designed with HVAC technicians, for HVAC technicians.</p>
                            <p class="text-white">Fully customizable and works with existing software.</p>
                            <p class="text-white">Coming Spring 2015</p>
                            
                            <div class="col-md-12">

								<!-- Early Access Subscribe. Emails List in subscribe.txt -->
								<%= form_for(@lead, remote: true) do |f| %>

								    <div class="row earlyaccess-box">
								        <div class="col-md-11" style="padding-left:0">
								            <p class="subscription-success"><i class="icon icon_check_alt2"></i> Thank you!  We will contact you shortly.</p>
								            <p class="subscription-failed"><i class="icon icon_close_alt2"></i> Something went wrong.  Please try again later.</p>

								            <div class="input-group">
								            	<%= f.text_field(:email, class: "form-control", style: "min-width:195px",
								            		placeholder: "Enter your Email Address") %>
								                <span class="input-group-btn">
								                    <%= f.submit "GET EARLY ACCESS", class: "btn btn-color", id: "lead_button"  %>
								                </span>
								            </div>
								        </div>
								    </div>

								<% end %>                     

                            </div>
                            <span class="text-white email-policy">We'll never spam you or share your email address.</span>
                            
                        </div><!-- /End Intro-Section -->
                    </div><!-- /End Col -->
                    <!-- App Showcase Image -->
                    <div class="col-sm-6 hidden-xs">
                        <div class="app-box">
                            <img src="/smartmvp/images/devices-app-blue.png" alt="" class="img-responsive">
                        </div>
                    </div>

                </div><!-- /End Row -->
            </div><!-- /End Container Hero-Section -->


        </div><!-- /End Background Overlay -->
    </header>
    <!-- =========================
         /END HEADER
    ============================== -->

    
    <!-- =================================
         SECTION ABOUT - INTRO FEATURES
    ====================================== -->
    <section class="intro-features" id="about">
        <div class="container">
            <!-- Padding -->
            <div class="wrapper-lg">
                <div class="row">
                    <!-- Section Header Title -->
                    <div class="col-xs-12">
                        <h2>Say goodbye to paperwork</h2>
                        <p class="large">Complete forms, capture signatures, and record equipment information from nearly any device, with or without internet access.</p>
                    </div>
                </div>
                <!-- Three Main Features with Icons -->
                <div class="row">
                    <div class="col-sm-4 intro-content">
                        <div class="icon-lg">
                            <i class="icon icon-documents"></i>
                        </div>
                        <h4>Built for HVAC</h4>
                        <p>Service tickets, proposals, inspection reports, and more.  Designed for usability in the field.</p>
                    </div>
                    <div class="col-sm-4 intro-content">
                        <div class="icon-lg">
                            <i class="icon icon-rss"></i>
                        </div>
                        <h4>Full Offline Access</h4>
                        <p>No internet connection required.  Automatically sync when a connection is available.</p>  
                    </div>
                    <div class="col-sm-4 intro-content">
                        <div class="icon-lg">
                            <i class="icon icon-browser"></i>
                        </div>
                        <h4>Easy to Customize</h4>
                        <p>More than custom fields.  We tailor our software to work for your business.</p>
                    </div>
                </div><!-- /End Row -->
            </div><!-- /End Wrapper -->
        </div><!-- /End Container -->
    </section>
    <!-- =============================
         /END INTRO FEATURES
    ============================== -->
    
    

    


    
    

    



    

    
    
    <!-- ==================================================
        FOOTER
    ======================================================= -->
    <footer class="footer dark-bg" id="footer">
        <div class="container">
            <div class="wrapper-lg">
                <div class="row">
                    <!-- Footer Left Col -->
                    <div class="col-md-5">
                            <!-- Logo -->
                            <a href="#top" class="scrollto" title="SmartMvp">
                                <span class="text-logo">ServiceLink</span>
                            </a>
                            <p class="footer-text">Mobile forms your technicians will love.</p>
                            <p class="footer-cta">Sign up now!
                                <a href="#top" class="btn btn-color">Get Early Access</a>
                            </p> 
                    </div>
                    <!-- Footer Contact Col -->
                    <div class="col-md-3">

                    </div>
                    <!-- Footer Right Col: Twitter Feed -->
                    <div class="col-md-4">
                        <h5 class="text-white">Contact Us</h5>
                        <div class="contact-item">
                            <div class="contact-icon">
                                <i class="icon icon_mail"></i>
                            </div>
                            <div class="contact-content">
                                <a href="mailto:info@servicelinkonline.com">info@servicelinkonline.com</a>
                            </div>
                        </div>
 
                    </div>

                    <!-- Footer Menu and Copy -->
                    <div class="row">
                        <div class="col-md-12">

                            <p class="footer-copy">&copy; 2014 ServiceLink. All rights reserved.</p>
                        </div>
                    </div>
                    
                </div><!-- End Row -->
            </div><!-- /End Wrapper -->
        </div><!-- /End Container -->
    </footer>


    <!-- =========================
         SCRIPTS 
    ============================== -->
    <!-- Not using the asset pipeline, but this is required to include jquery_ujs for remote (ajax) form -->
    <!-- Also includes jquery -->
    <%= javascript_include_tag :application %>
    <!-- <script src="/smartmvp/js/plugins/jquery1.11.0.min.js"></script> -->
    <script src="/smartmvp/js/plugins/bootstrap.min.js"></script>

    <!-- Custom Script -->
    <script src="/smartmvp/js/custom.js"></script>

    

</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/create.js.erb
//This file is included to respond to format.js without an error
//See leads.js for ajax success/error handling
//console.log('js.erb response');

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leads</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.email %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>